author:
  twitter: joaorcabrita
collections:
  prof_exp:
    sort_by: date
  patterns:
    output: true
  talks:
    sort_by: date

defaults:
  - scope:
      path: ""
      type: 'patterns'
    values:
      layout: 'default'
      categories:
        - pattern
  - scope:
      path: ""
      type: 'prof_exp'
    values:
      recent: false
encoding: UTF-8
exclude:
- .idea
- vendor
- .ruby-lsp

plugins:
- jekyll-seo-tag

safe: true
social:
  links:
  - https://twitter.com/joaorcabrita
  - https://instagram.com/o_joao_cabrita
  - https://www.linkedin.com/in/joaorcabrita

url: http://kewne.github.io

title: Jo√£o Cabrita's Home Page

twitter:
  username: joaorcabrita


whitelist:
  - jekyll-seo-tag
